### ISSUE TITLE
Neofetch config issue

### ISSUE THREAD

**Issue by N0tTaiko** [ilham25/dotfiles-aether#2]
the neofetch config doesnt display the image
![image](https://user-images.githubusercontent.com/84384778/171989804-ac684889-073d-4dbb-ac97-c4733d68c312.png)

**Comment by samuelnihbos** [comment]
have u installed w3m or ueberzug?

**Comment by ilham25** [comment]
you need to install w3m to show image in terminal

**Comment by N0tTaiko** [comment]
> have u installed w3m or ueberzug?

i already have w3m, the image is blinky then it disappear

**Comment by N0tTaiko** [comment]
> you need to install w3m to show image in terminal

already dude

**Comment by ilham25** [comment]
I think that's not related to my config because it work on my machine. Also can you try in another terminal? I'm using urxvt and it work properly

**Comment by N0tTaiko** [comment]
> I think that's not related to my config because it work on my machine. Also can you try in another terminal? I'm using urxvt and it work properly

alright ill try it
im using kitty btw

**Comment by N0tTaiko** [comment]
its not working, i tried on xfce terminal,urxvt, and xterm, it just blinky for some sec then its disappear

**Comment by ilham25** [comment]
Hmm that's weird, i never encountered this issue before. I think you should try another neofetch config
